In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
arr=np.array([10, 20, 30, 40, 50])

In [4]:
print(arr)


[10 20 30 40 50]


In [6]:
print("Shape of NumPy array:",arr.shape)

Shape of NumPy array: (5,)


In [7]:
ab=pd.Series([23, 45, 65, 72, 89])

In [8]:
print(ab)


0    23
1    45
2    65
3    72
4    89
dtype: int64


In [9]:
arr_d1=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [13]:
print(arr_d1)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
arr_md=np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])

In [12]:
print(arr_md)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
zeros=np.zeros((4,5))

In [16]:
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
ones=np.ones((5,4))

In [ ]:
print(ones